apiVersion: v1
kind: Namespace
metadata:
  name: theia

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-workspace-pvc
  namespace: theia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-ide
  namespace: theia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theia-ide
  template:
    metadata:
      labels:
        app: theia-ide
    spec:
      containers:
      - name: theia-ide
        image: theia-ide:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: workspace
          mountPath: /home/project
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: theia-workspace-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: theia-ide-service
  namespace: theia
spec:
  selector:
    app: theia-ide
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort