database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: the_blogger

server:
  port: 8080
  env: development

// .env
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=blog_db
JWT_SECRET=your-secret-key